[versions]
activity-compose = "1.8.0"
androidx-junit = "1.1.5"
appcompat = "1.6.1"
material3 = "1.2.0-alpha10"
coil = "2.4.0"
compose-bom = "2023.09.00"
constraintlayout = "2.1.4"
core-ktx = "1.12.0"
espresso-core = "3.5.1"
junit = "4.13.2"
koin-bom = "3.5.1"
koin-annotations = "1.3.0"
ktlint = "11.5.1"
lifecycle-runtime-ktx = "2.6.2"
mockk = "1.13.8"
mockk-android = "1.13.8"
room-version = "2.6.0"
#room-compiler = "2.6.0"
#room-ktx = "2.6.0"
#room-runtime = "2.6.0"
timber = "5.0.1"
nav-compose = "2.7.4"


[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }


[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "nav-compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-material3-window = { module ="androidx.compose.material3:material3-window-size-class" , version.ref = "material3" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk-android" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-version" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-version" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-version" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
compose-ui-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

